controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ackermann_steering_controller:
  ros__parameters:
    type: 'ackermann_steering_controller/AckermannSteeringController'
    wheelbase: 1.7
    traction_track_width: 1.0
    steering_track_width: 1.0
    traction_wheels_radius: 0.3
    steering_wheels_radius: 0.3
    reference_timeout: 2.0 # In s. Timeout to stop if no cmd_vel is received
    traction_joints_names: ['rear_right_wheel_joint', 'rear_left_wheel_joint']
    steering_joints_names: ['right_wheel_steering_joint', 'left_wheel_steering_joint']
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: false
