mechanum_controller:
   ros__parameters:
      type: "mechanum_controller/MechanumController"
      frame:
         odom_frame_id: odom
         base_frame_id: base_link
      speed:
         wheel:
            enable: false
            max_velocity: 7.0
            max_acceleration: 5.0
            max_jerk: 100.0
         planar:
            enable: false
            x:
               max_velocity: 0.8
               max_acceleration: 0.1
               max_jerk: 50.0
            y:
               max_velocity: 0.5
               max_acceleration: 0.1
               max_jerk: 50.0
            angular:
               max_velocity: 1.7
               max_acceleration: 1.5
               max_jerk: 25.0
      time:
         cmd_vel_timeout: 2.0 #[s]
         teleop_sub_timeout: 1.0 #[s]      

diagnostic_controller:
   ros__parameters:
      type: "diagnostic_controller/DiagnosticController"

aero_controller:
   ros__parameters:
      type: "aero_controller/AeroController"

status_controller:
   ros__parameters:
      type: "aero_controller/StatusController"

robotstatus_controller:
   ros__parameters:
      type: "aero_controller/RobotStatusController"
      
config_controller:
   ros__parameters:
      type: "config_controller/ConfigController"

