teleop_twist_joy_node:
   ros__parameters:
      update_rate: 50 # Hz
      require_enable_button: true
      enable_button: 4
      enable_turbo_button: 6
      axis_linear:
         x:  1
         y:  3
         z: -1
      axis_angular:
         yaw:    0
         pitch: -1
         roll:  -1
      scale_linear:
         x: 0.3
         y: 0.3
         z: 0.0
      scale_linear_turbo:
         x: 0.8
         y: 0.8
         z: 0.0
      scale_angular:
         yaw:   1.0
         pitch: 0.0
         roll:  0.0
      scale_angular_turbo:
         yaw:   1.7
         pitch: 0.0
         roll:  0.0