name: gz_ros2_control CI - Jazzy

on:
  workflow_dispatch:
  pull_request:
    branches: [ jazzy ]
  push:
    branches: [ jazzy ]
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 4 * * MON-FRI'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros-distro: "jazzy"
            ros-repo-packages: "-testing"
          - ros-distro: "jazzy"
            ros-repo-packages: ""
    env:
      ROS_DISTRO: ${{ matrix.ros-distro }}
    container:
      image: ghcr.io/ros-controls/ros:${{ matrix.ros-distro }}-ubuntu${{ matrix.ros-repo-packages }}
    steps:
    - name: Checkout code
      if: github.event_name != 'schedule'
      uses: actions/checkout@v4
    - name: Checkout code for scheduled workflow
      if: github.event_name == 'schedule'
      uses: actions/checkout@v4
      with:
        ref: jazzy
    - name: Setup colcon workspace
      id: configure
      shell: bash
      run: |
        apt-get update
        rosdep update
        rosdep install --from-paths ./ -i -y --rosdistro ${ROS_DISTRO}
    - name: Build project
      id: build
      run: |
        . /opt/ros/${ROS_DISTRO}/local_setup.sh
        colcon build --packages-up-to gz_ros2_control_demos gz_ros2_control_tests
    - name: Run tests
      id: test
      run: |
        . /opt/ros/${ROS_DISTRO}/local_setup.sh
        colcon test --event-handlers console_direct+ --packages-select gz_ros2_control gz_ros2_control_demos gz_ros2_control_tests
        colcon test-result
