controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
      interfaces:
         - position
         - velocity

      joint_not_publish:
         - wheel_front_left
         - wheel_front_right
         - wheel_rear_left
         - wheel_rear_right
