lifter_controller:
   ros__parameters:
     type: joint_trajectory_controller/JointTrajectoryController
     joints:
       - knee_joint
       - ankle_joint

     command_interfaces:
       - position

     state_interfaces:
       - position

     action_monitor_rate: 20.0
     allow_partial_joints_goal: false
     interpolate_from_desired_state: true
     allow_integration_in_goal_trajectories: true
     stop_trajectory_duration: 0.2
     constraints:
       goal_time: 1.0
       stopped_velocity_tolerance: 0.01
